### ISSUE TITLE
TODO: 使用 Github Action 自动构建，并自动上传到平台

### ISSUE THREAD

**Issue by matyhtf** [swoole/swoole-cli#101]
使用 `Github Action` 自动构建，并上传发布：

发布
----

- [ ] `Github swoole-src releases` 
- [ ]  `Gitee swoole-src releases` 
- [ ] `Github swoole-clireleases` 
- [ ] `Gitee swoole-cli releases` 
- [ ] 腾讯云 `OSS` （`swoole.com/download` 页面）

平台
----
- [ ] Linux x86-64
- [ ] Linux arm64
- [ ] macOS x86-64
- [ ] macOS arm64
- [ ] Windows x86-64 cygwin

**Comment by jingjingxyk** [comment]
编译挺耗费时间的


https://github.com/jingjingxyk/swoole-cli/actions/runs/4592217182/jobs/8109054511#step:9:1651

https://github.com/jingjingxyk/swoole-cli/actions/runs/4592217182/jobs/8109054511

https://github.com/swoole/swoole-cli/actions/runs/4577652169

**Comment by jingjingxyk** [comment]
使用 qemu-user-static  linux arm64 更慢,

https://github.com/jingjingxyk/swoole-cli/actions/runs/4594411454/jobs/8113413373
